### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by Cyber-Pop** [AzuraApple/celestia#10]
Whenever i try to perform a commands, it works fine. But when someone else does that command it doesn't works and logs errors on console.
The logs are-
```
Uncaught Promise Error:  TypeError: Cannot read property 'user' of null
    at Object.check (/home/container/config.js:51:82)
    at Luna.permlevel (/home/container/celestia.js:34:24)
    at module.exports.run (/home/container/events/message.js:41:31)
Uncaught Promise Error:  TypeError: Cannot read property 'user' of null
    at Object.check (/home/container/config.js:51:82)
    at Luna.permlevel (/home/container/celestia.js:34:24)
    at module.exports.run (/home/container/events/message.js:41:31)
Uncaught Promise Error:  TypeError: Cannot read property 'user' of null
    at Object.check (/home/container/config.js:51:82)
    at Luna.permlevel (/home/container/celestis.js:34:24)
    at module.exports.run (/home/container/events/message.js:41:31)
```

**Comment by Cyber-Pop** [comment]
another error-
When i do the eval command it says -
```
Uncaught Promise Error:  TypeError: this.client.clean is not a function
    at Eval.run (/home/container/commands/Bot Owner/eval.js:27:69)
    at module.exports.run (/home/container/events/message.js:72:9)
```

**Comment by Cyber-Pop** [comment]
another error in the Kaomoji command-
```
Uncaught Promise Error:  ReferenceError: Cannot access 'face' before initialization
    at Kaomoji.run (/home/container/commands/Random Response/kaomoji.js:16:53)
    at module.exports.run (/home/container/events/message.js:72:9)
```
